name: build-and-push-telicent-test
on:
  push:
    branches:
      - main
    paths:
      - CHANGELOG.md

jobs:
  get_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: get-version
        id: get-version
        run: echo "::set-output name=CURRENT_VERSION::`cat version.txt`"
    outputs:
      version: ${{ steps.get-version.outputs.CURRENT_VERSION }}

  publish_deployment_image_to_registries:
    needs:
      - get_version
    uses: Telicent-io/telicent-test/.github/workflows/push-to-registries-python.yml@main
    with:
      APP_NAME: telicent-ndt-write-api-demo
      DOCKERFILE: Dockerfile
      PATH: .
      VERSION: ${{ needs.get_version.outputs.version }}
    secrets: inherit
